# This is the base image from which we're building. 
# "oven/bun" is a pre-made image that has Node.js and bun pre-installed.
FROM oven/bun

# Set the working directory in the Docker image to "/client".
# All subsequent commands will run in this directory.
WORKDIR /client

# Copy all files from your project into the Docker image.
# The "." refers to the current directory (where your Dockerfile and application code is).
COPY . .

# Run the bun install command. 
# This retrieves all the necessary dependencies for the project.
RUN bun install

# Expose port 3000 of the Docker container.
# This is standard http port for a web server.
EXPOSE 3000

# Expose port 24678 of the Docker container.
# This could be a port the application uses for something else, like live reloading.
EXPOSE 24678

# The CMD directive defines the command to be executed when running a container from this image.
# Here, it's running the application in development mode and making it listen on all interfaces (0.0.0.0).
CMD ["bun", "--bun", "run", "dev", "--", "--host", "0.0.0.0"]