from node:16-alpine

RUN mkdir -p /client/node_modules && chown -R node:node /client
WORKDIR /client

COPY ["package.json", "package-lock.json*", "./"]

USER node

# Install Node modules
RUN npm ci

# Copy over rest of the project files
COPY --chown=node:node . .

RUN npm run build

EXPOSE 3000
CMD ["node", "./build"]