from node:16-alpine

RUN mkdir -p /client/node_modules && chown -R node:node /client
USER node
WORKDIR /client

# # Set the Node environment to development to ensure all packages are installed
# ENV NODE_ENV development
# ENV NODE_OPTIONS=--inspect=0.0.0.0:9229

# Change our current working directory
# WORKDIR /usr/src/app

# Copy over `package.json` and lock files to optimize the build process
# COPY ["package.json", "package-lock.json*", "./"]
COPY --chown=node:node package*.json ./


# Install Node modules
RUN npm i

# Copy over rest of the project files
COPY --chown=node:node . .

# Expose port 3000 for the SvelteKit app and 24678 for Vite's HMR
EXPOSE 5173
EXPOSE 24678

# Run `yarn dev` and set the host to 0.0.0.0 so we can access the web app from outside
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]