
version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    tty: true
    env_file: ./client/.env

    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - ./client:/client
      - /client/node_modules
    # networks:
    #   - properlife_network
      
  # pocketbase:
  #   build:
  #     context: ./pocketbase
  #     dockerfile: Dockerfile
  #   ports:
  #     - 8090:8090
  #     # - 8090:8090
  #   volumes:
  #     - ./pocketbase/pb_migrations:/pb/pb_migrations
  #     - ./pocketbase/pb_hooks:/pb/pb_hooks
  #   networks:
  #     - properlife_network

# networks:
#   properlife_network:
#     driver: bridge
