
version: "3"

services:
  # content_dashboard_svelte:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.prod
  #   restart: always
  #   tty: true
  #   env_file: ./client/.env

  #   ports:
  #     - 3070:3000
  #   networks:
  #     - webappnetwork_cd
  #     - nginx_network

  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - webrootfiles:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - dhparam:/etc/ssl/certs
    depends_on:
      - pocketbase
    networks:
      - properlife_network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webrootfiles:/var/www/html
    depends_on:
      - webserver
    # command: certonly -v --webroot --webroot-path=/var/www/html --email properlifeapp@gmail.com --agree-tos --no-eff-email --staging -d properlife.app -d www.properlife.app
    command: certonly -v --webroot --webroot-path=/var/www/html --email properlifeapp@gmail.com --agree-tos --no-eff-email --force-renewal -d properlife.app -d www.properlife.app


  pocketbase:
    build:
      context: ./pocketbase
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    volumes:
      - ./pocketbase/pb_migrations:/pb/pb_migrations
      - ./pocketbase/pb_hooks:/pb/pb_hooks
    networks:
      - properlife_network

networks:
  properlife_network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  webrootfiles:
    driver: local
    driver_opts:
      type: none
      device: /root/properlife/nginx-conf/web/
      o: bind
  dhparam:
    driver: local
    driver_opts:
      type: none
      device: /root/properlife/dhparam
      o: bind


